plugins {
    id 'com.github.johnrengelman.shadow' version "${shadow_version}"
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.75'
    id 'java'
}


version = '2.0'
group = 'com.github.awesomeshot5051'
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
java{
    withSourcesJar()
}

jar {
    manifest {
        attributes(['Automatic-Module-Name'   : 'com.awesomeshot5051.corelib'])
    }
}

processResources {
    filesMatching('**/*.toml') {
        expand 'mod_version': mod_version,
                'neoforge_dependency': neoforge_dependency,
                'minecraft_version': minecraft_version
    }
}
neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        implementation 'com.github.jitpack:gradle-simple:1.0'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/resources/META-INF"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata as Task
tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
javadoc {
    failOnError = false
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

