plugins {
//    id 'net.neoforged.gradle.userdev' version "${neogradle_version}"
//    id 'net.neoforged.gradle.mixin' version "${neogradle_mixin_version}"
    id 'com.github.johnrengelman.shadow' version "${shadow_version}"
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.74'
    // Plugin to use the settings.xml for authentication
//    id 'net.linguica.maven-settings' version "${maven_settings_version}"
}

//apply plugin: 'maven-publish'
//apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

java{
    withSourcesJar()
}

jar {
    manifest {
        attributes(['Automatic-Module-Name'   : 'com.awesomeshot5051.corelib'])
    }
}

processResources {
    filesMatching('**/*.toml') {
        expand 'mod_version': mod_version,
                'neoforge_dependency': neoforge_dependency,
                'minecraft_version': minecraft_version
    }
}
neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
//tasks.register('apiJar', Jar) {
//    archiveClassifier = 'api'
//    from sourceSets.main.output
//    exclude 'de/maxhenkel/corelib/dev'
//}
tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/resources/META-INF"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata
tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

tasks.matching(it -> it.name.startsWith("publish")).configureEach {
    it.dependsOn shadowJar
}

javadoc {
    failOnError = false
}

artifacts {
    archives jar
//    archives apiJar
    archives javadocJar
    archives sourcesJar
}

//publishing {
//    publications {
//        mavenJava(MavenPublication) {
//            artifact jar
//            artifact apiJar
//            artifact javadocJar
//            artifact sourcesJar
//        }
//    }
//    repositories {
//        maven {
//            name = 'henkelmax.public'
//            url = 'https://maven.maxhenkel.de/repository/public'
//        }
//    }

