org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

java_version=21

mod_loader=neoforge
minecraft_version=1.21
neoforge_version=21.1.97
neoforge_dependency=[21.1.0,)
maven_settings_version=0.5

# Mod information
mod_version=1.21-2.1.4
mod_id=corelib
mod_name=Corelib

# Script configuration
enable_curseforge_upload=false
enable_modrinth_upload=false
enable_mod_update=false
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
loader_version_range=[4,)
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1, 1.22)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.97
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.0,)
# Gradle plugins
#mod_gradle_script_version=1.0.32
neogradle_version=7.0.+
shadow_version=8.1.1
neogradle_mixin_version=7.0.+
