modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
[[mods]]
modId = "corelib"
displayName = "Mob Farms"
logoFile = "../assets/corelib/textures/gui/icons/icon.png"
authors = "awesomeshot5051"
description = '''Mod Farms'''
[[dependencies.corelib]]
modId = "neoforge"
type = "required"
version = "1.0.0"
ordering = "NONE"
side = "BOTH"
[[dependencies.corelib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"